
FROM maven:3.8.6-eclipse-temurin-17 AS build
WORKDIR /app/back
COPY src/back/calculator-backend/pom.xml .
RUN mvn dependency:go-offline
COPY src/back/calculator-backend/src ./src
RUN mvn package -DskipTests
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/back/target/calculator-backend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]