services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./src/back/calculator-backend:/app/back
    networks:
      - calc-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - calc-network

networks:
  calc-network:
    driver: bridge